export const Types = {
  AUTH_REGISTER: "AUTH_REGISTER",
  AUTH_REGISTER_FAILED: "AUTH_REGISTER_FAILED",
  SET_ALERT: "SET_ALERT",
  CLOSE_ALERT: "CLOSE_ALERT",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_CURRENT_USER_FAILED: "GET_CURRENT_USER_FAILED",
};
